package ai.jevguard;
import android.app.*;
import android.os.*;
import android.content.*;
import android.content.pm.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.view.*;
import android.view.inputmethod.*;
import android.widget.*;
import android.text.*;
import java.io.*;
import java.text.DateFormat;
import java.util.*;
import java.util.concurrent.*;
import org.json.*;

public class MainActivity extends Activity {
 final int BG=Color.rgb(10,17,28),CARD=Color.rgb(21,33,49),INK=Color.rgb(235,241,250),MUTED=Color.rgb(155,172,191),GREEN=Color.rgb(117,230,177),AMBER=Color.rgb(255,202,117),RED=Color.rgb(255,139,143);
 LinearLayout root,body,nav; TextView status; JSONObject current; JSONArray history=new JSONArray(); boolean busy=false; String page="Scan";SecretStore secrets; final ExecutorService work=Executors.newSingleThreadExecutor();
 interface Task{void run()throws Exception;}
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);secrets=new SecretStore(this);loadHistory();if(history.length()>0)current=history.optJSONObject(0);show("Scan");}
 int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+.5f);}
 GradientDrawable shape(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}
 TextView txt(String s,int size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setLineSpacing(dp(3),1);return t;}
 void addText(LinearLayout parent,String s,int size,int color){TextView t=txt(s,size,color);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(10);parent.addView(t,p);}
 LinearLayout box(){LinearLayout b=new LinearLayout(this);b.setOrientation(1);b.setPadding(dp(18),dp(18),dp(18),dp(16));b.setBackground(shape(CARD,20));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(14);body.addView(b,p);return b;}
 Button button(LinearLayout parent,String text,boolean primary,Runnable action){Button b=new Button(this);b.setText(text);b.setTextSize(14);b.setAllCaps(false);b.setTextColor(primary?BG:INK);b.setBackground(shape(primary?GREEN:Color.rgb(36,51,71),13));b.setMinHeight(dp(50));b.setPadding(dp(12),dp(10),dp(12),dp(10));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(8);parent.addView(b,p);b.setOnClickListener(v->{if(busy){toast("A scan is running. Please wait.");return;}action.run();});return b;}
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
 void show(String name){page=name;root=new LinearLayout(this);root.setOrientation(1);root.setBackgroundColor(BG);root.setPadding(dp(20),dp(16),dp(20),dp(10));root.setOnApplyWindowInsetsListener((v,insets)->{android.graphics.Insets i=insets.getInsets(WindowInsets.Type.systemBars());v.setPadding(dp(20)+i.left,dp(12)+i.top,dp(20)+i.right,dp(8)+i.bottom);return insets;});
 // API 28/29 uses legacy insets; newer devices use edge-to-edge system bars.
 if(Build.VERSION.SDK_INT<30)root.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(dp(20)+i.getSystemWindowInsetLeft(),dp(12)+i.getSystemWindowInsetTop(),dp(20)+i.getSystemWindowInsetRight(),dp(8)+i.getSystemWindowInsetBottom());return i;});
 TextView brand=txt("JEV / GUARD",15,GREEN);brand.setLetterSpacing(.18f);brand.setTypeface(null,Typeface.BOLD);root.addView(brand);
 TextView title=txt(name.equals("Scan")?"Know what you install.":name.equals("Apps")?"Inspect your apps.":name.equals("History")?"Your scan history.":"Connected on your terms.",27,INK);title.setTypeface(null,Typeface.BOLD);title.setPadding(0,dp(15),0,dp(12));root.addView(title);
 status=txt(busy?"Working…":"APK inspection · Personal preview",12,MUTED);status.setPadding(0,0,0,dp(12));status.setAccessibilityLiveRegion(View.ACCESSIBILITY_LIVE_REGION_POLITE);root.addView(status);
 ScrollView sc=new ScrollView(this);sc.setFillViewport(true);body=new LinearLayout(this);body.setOrientation(1);sc.addView(body);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));
 nav=new LinearLayout(this);nav.setPadding(0,dp(10),0,0);for(String item:new String[]{"Scan","Apps","History","Settings"}){TextView t=txt(item,13,item.equals(name)?GREEN:MUTED);t.setGravity(Gravity.CENTER);t.setPadding(0,dp(14),0,dp(14));t.setTypeface(null,Typeface.BOLD);nav.addView(t,new LinearLayout.LayoutParams(0,dp(50),1));t.setOnClickListener(v->{if(!busy)show(item);else toast("Please wait for the current check.");});}root.addView(nav);setContentView(root);
 switch(name){case "Apps":apps();break;case "History":history();break;case "Settings":settings();break;default:home();}
 }
 void home(){LinearLayout hero=box();addText(hero,"INSPECT BEFORE INSTALLING",11,GREEN);addText(hero,"A closer look at your APK",21,INK);addText(hero,"Review permissions and signing identity on your phone. Add cloud evidence when you choose.",14,MUTED);button(hero,"Choose an APK",true,()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE);try{startActivityForResult(i,10);}catch(Exception e){toast("No file picker available.");}});
 if(current!=null)report(current);else{LinearLayout b=box();addText(b,"No scans yet",18,INK);addText(b,"Select an APK, or open Apps to inspect an installed app. Nothing is uploaded during local inspection.",14,MUTED);}
 LinearLayout foot=box();addText(foot,"Evidence, not a safety guarantee",15,AMBER);addText(foot,"This preview checks APK metadata. It does not execute files, monitor behavior, provide real-time protection, or inspect other apps' private data. Jev is an experimental review aid, not a malware engine.",13,MUTED);
 }
 String when(long t){return t<=0?"Unknown":DateFormat.getDateTimeInstance(DateFormat.MEDIUM,DateFormat.SHORT).format(new Date(t));}
 String join(JSONArray a){if(a==null||a.length()==0)return "None declared";StringBuilder b=new StringBuilder();for(int i=0;i<a.length();i++){if(i>0)b.append("\n\n");b.append(a.optString(i));}return b.toString();}
 void details(String title,String text){TextView t=txt(text,14,INK);t.setTextIsSelectable(true);t.setPadding(dp(22),dp(15),dp(22),dp(15));ScrollView s=new ScrollView(this);s.addView(t);new AlertDialog.Builder(this).setTitle(title).setView(s).setPositiveButton("Close",null).show();}
 void report(JSONObject r){LinearLayout b=box();addText(b,"LOCAL INSPECTION",11,GREEN);addText(b,r.optString("label"),20,INK);addText(b,r.optString("package")+"  ·  "+r.optString("version"),13,MUTED);addText(b,when(r.optLong("time"))+"\n"+String.format(Locale.ROOT,"%.1f MB",r.optLong("bytes")/1048576.0)+"  ·  Target Android API "+r.optInt("target_sdk"),12,MUTED);
 JSONArray f=r.optJSONArray("findings");int count=f==null?0:f.length();addText(b,count==0?"No listed capability flags":"Review "+count+" capability flags",19,count==0?INK:AMBER);addText(b,"Requested capabilities are not proof of use or malware. No listed flags does not mean safe.",12,MUTED);if(count>0)addText(b,join(f),14,INK);
 if(r.optBoolean("split_base_only"))addText(b,"Partial coverage: only the installed base APK was inspected. Split APKs were not inspected.",13,AMBER);
 button(b,"Permissions ("+r.optJSONArray("permissions").length()+")",false,()->details("Requested permissions",join(r.optJSONArray("permissions"))));
 button(b,"File hash & signing identity",false,()->{String cert="Certificate information unavailable.";try{cert=r.getJSONArray("certificates").toString(2);}catch(Exception ignored){}details("File identity","SHA-256\n"+r.optString("sha256")+"\n\nSigning certificates\n"+cert+"\n\nCertificate metadata identifies the signer. This app does not independently verify APK signature integrity or publisher trust.");});
 LinearLayout v=box();addText(v,"VIRUSTOTAL",11,GREEN);JSONObject vt=r.optJSONObject("vt");if(vt==null){addText(v,"Reputation not checked",19,INK);addText(v,"Look up existing engine reports using only this APK's SHA-256 hash.",13,MUTED);}else if("unknown".equals(vt.optString("status"))){addText(v,"Unknown to VirusTotal",19,AMBER);addText(v,"No existing report was found. This is not a clean result.",13,MUTED);}else{int m=vt.optInt("malicious"),s=vt.optInt("suspicious");addText(v,RiskRules.verdict(m,s),19,m>0?RED:s>0?AMBER:INK);addText(v,m+" malicious · "+s+" suspicious\nAnalysis: "+when(vt.optLong("analysis_date")*1000),14,MUTED);addText(v,"Reports may be old. Zero detections is not a guarantee; engines can also produce false positives.",12,MUTED);button(v,"Engine report details",false,()->{try{details("VirusTotal report",vt.getJSONObject("stats").toString(2)+"\n\n"+join(vt.optJSONArray("detections")));}catch(Exception e){toast("Report unavailable");}});}
 if(r.has("vt_error"))addText(v,"Last attempt failed: "+r.optString("vt_error"),13,AMBER);
 button(v,vt==null?"Check hash with VirusTotal":"Refresh hash report",false,()->cloud(r,false));
 LinearLayout j=box();addText(j,"JEV / TYPESAFE",11,GREEN);JSONObject jev=r.optJSONObject("jev");if(jev==null){addText(j,"AI review not run",19,INK);addText(j,"Jev reviews permissions and available reputation evidence to suggest whether closer review is useful.",13,MUTED);}else{String choice=jev.optString("choice");String label="review".equals(choice)?"Closer review suggested":"limited_signals".equals(choice)?"Limited concern in supplied evidence":"Insufficient evidence";addText(j,label,19,"review".equals(choice)?AMBER:INK);addText(j,"Model confidence: "+Math.round(jev.optDouble("confidence")*100)+"%\n"+jev.optString("model")+" · "+when(jev.optLong("checked_at")),13,MUTED);addText(j,"Confidence describes the model's choice distribution, not the chance this APK is safe or malicious. This assessment has not been validated as a malware detector.",12,MUTED);button(j,"Review probabilities",false,()->{try{details("Jev assessment",jev.getJSONObject("probabilities").toString(2));}catch(Exception ignored){}});}
 if(r.has("jev_error"))addText(j,"Last attempt failed: "+r.optString("jev_error"),13,AMBER);
 button(j,"Ask Jev to review evidence",true,()->cloud(r,true));button(j,"Export report",false,()->{current=r;Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/json").addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_TITLE,"jev-guard-"+r.optString("package")+".json");startActivityForResult(i,20);});
 }
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;Uri uri=data.getData();if(request==10){run("Inspecting APK locally…",()->{File tmp=File.createTempFile("inspect-",".apk",getCacheDir());try{try(InputStream in=getContentResolver().openInputStream(uri);OutputStream out=new FileOutputStream(tmp)){if(in==null)throw new IOException("Cannot open file");byte[] buf=new byte[65536];long total=0;int n;while((n=in.read(buf))!=-1){total+=n;if(total>Scanner.MAX_BYTES)throw new IOException("APK exceeds the 300 MB inspection limit.");out.write(buf,0,n);}}JSONObject report=Scanner.scan(this,tmp,"Selected APK",false);save(report);current=report;}finally{tmp.delete();}});}else if(request==20&&current!=null){final String json=current.toString();run("Exporting report…",()->{try(OutputStream out=getContentResolver().openOutputStream(uri,"wt")){if(out==null)throw new IOException("Cannot write report");out.write(json.getBytes("UTF-8"));}});}}
 void run(String message,Task task){busy=true;status.setText(message);work.execute(()->{String error=null;try{task.run();}catch(Exception e){error=e instanceof java.net.SocketTimeoutException?"Connection timed out. Check your network and retry.":e.getMessage();if(error==null)error="Operation could not be completed.";}final String err=error;runOnUiThread(()->{if(isFinishing()||isDestroyed())return;busy=false;show(page);if(err!=null)new AlertDialog.Builder(this).setTitle("Could not complete check").setMessage(err).setPositiveButton("OK",null).show();});});}
 void cloud(JSONObject r,boolean jev){String provider=jev?"Jev":"VirusTotal",key;try{key=secrets.get(jev?"jev":"vt");}catch(Exception e){toast("Could not unlock key. Re-enter it in Settings.");return;}if(key.isEmpty()){new AlertDialog.Builder(this).setTitle(provider+" key needed").setMessage("Add your own "+provider+" API key in Settings. Local inspection works without keys.").setPositiveButton("Settings",(d,w)->show("Settings")).setNegativeButton("Cancel",null).show();return;}
 String content;try{content=jev?"Send the following app metadata and available reputation summary to TypeSafe? No APK bytes or API keys are included in this evidence.\n\n"+Api.evidence(r).toString(2):"Send this file's SHA-256 hash to VirusTotal to retrieve an existing report? No APK bytes are uploaded.\n\n"+r.optString("sha256");}catch(Exception e){toast("Cannot prepare evidence");return;}
 TextView t=txt(content,13,INK);t.setPadding(dp(20),dp(10),dp(20),dp(10));ScrollView scroll=new ScrollView(this);scroll.addView(t);final String k=key;
 new AlertDialog.Builder(this).setTitle("Check with "+provider+"?").setView(scroll).setNegativeButton("Cancel",null).setPositiveButton("Send & check",(d,w)->run("Checking with "+provider+"…",()->{String field=jev?"jev":"vt";try{JSONObject response=jev?Api.jev(r,k):Api.virusTotal(r.getString("sha256"),k);r.put(field,response);r.remove(field+"_error");if(!jev&&r.has("jev")){r.remove("jev");r.remove("jev_error");}}catch(Exception e){r.put(field+"_error",e.getMessage()==null?"Connection failed":e.getMessage());save(r);throw e;}save(r);current=r;page="Scan";})).show();
 }
 void apps(){LinearLayout note=box();addText(note,"Select an installed app",18,INK);addText(note,"Inspection reads its base APK. User apps are listed below; Android may limit visibility. Scans stay local until you request a cloud check.",13,MUTED);
 EditText query=new EditText(this);query.setSingleLine(true);query.setHint("Search name or package");query.setTextColor(INK);query.setHintTextColor(MUTED);body.addView(query);Switch system=new Switch(this);system.setText("Include system apps");system.setTextColor(MUTED);system.setPadding(dp(8),dp(12),dp(8),dp(12));body.addView(system);LinearLayout list=new LinearLayout(this);list.setOrientation(1);body.addView(list);
 // Package listing is requested explicitly on this screen; scanning is always per-app.
 List<PackageInfo> all=getPackageManager().getInstalledPackages(0);Collections.sort(all,(a,b)->a.packageName.compareToIgnoreCase(b.packageName));
 Runnable filter=()->{list.removeAllViews();String q=query.getText().toString().toLowerCase(Locale.ROOT);int count=0;for(PackageInfo p:all){if(p.applicationInfo==null)continue;boolean sys=(p.applicationInfo.flags&ApplicationInfo.FLAG_SYSTEM)!=0;if(sys&&!system.isChecked())continue;String label;try{label=p.applicationInfo.loadLabel(getPackageManager()).toString();}catch(Exception e){label=p.packageName;}if(!label.toLowerCase(Locale.ROOT).contains(q)&&!p.packageName.toLowerCase(Locale.ROOT).contains(q))continue;final PackageInfo target=p;button(list,label+"\n"+p.packageName,false,()->{page="Scan";show(page);run("Inspecting installed APK…",()->{JSONObject r=Scanner.scan(this,new File(target.applicationInfo.sourceDir),"Installed base APK",target.applicationInfo.splitSourceDirs!=null&&target.applicationInfo.splitSourceDirs.length>0);save(r);current=r;});});count++;}if(count==0)addText(list,"No matching apps are visible.",14,MUTED);};system.setOnCheckedChangeListener((v,c)->filter.run());query.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int start,int count,int after){}public void onTextChanged(CharSequence s,int start,int before,int count){filter.run();}public void afterTextChanged(Editable e){}});filter.run();}
 void history(){LinearLayout b=box();addText(b,history.length()+" saved inspections",19,INK);addText(b,"Stored on this phone. Open a report to review its evidence or export it.",13,MUTED);for(int i=0;i<history.length();i++){JSONObject r=history.optJSONObject(i);if(r==null)continue;button(b,r.optString("label")+"\n"+when(r.optLong("time")),false,()->{current=r;show("Scan");});}if(history.length()>0)button(b,"Clear scan history",false,()->new AlertDialog.Builder(this).setTitle("Delete local scan history?").setMessage("Exported reports are not affected.").setNegativeButton("Cancel",null).setPositiveButton("Delete",(d,w)->{history=new JSONArray();current=null;getSharedPreferences("reports",0).edit().remove("history").commit();show("History");}).show());}
 void settings(){LinearLayout b=box();addText(b,"Your API connections",20,INK);addText(b,"Add personal API keys here. Keys are encrypted using Android Keystore, excluded from backups, and sent only to the matching provider over HTTPS. Provider access, quotas and charges apply.",13,MUTED);for(String p:new String[]{"jev","vt"}){String name=p.equals("jev")?"Jev / TypeSafe":"VirusTotal";boolean configured=false;try{configured=!secrets.get(p).isEmpty();}catch(Exception ignored){}button(b,name+" · "+(configured?"Key saved":"Not connected"),false,()->keyDialog(p,name));}
 LinearLayout p=box();addText(p,"Privacy & scope",19,INK);addText(p,"• Local inspection: APK metadata and SHA-256 remain on this phone.\n\n• VirusTotal: sends the SHA-256 hash only. No file upload.\n\n• Jev: sends package details, permissions, local flags and available reputation summary after confirmation.\n\n• No analytics, automatic cloud checks, background monitoring, automatic deletion, or accessibility access.\n\n• Last 50 reports retained locally. Exported reports contain package identity and permissions, never API keys.",14,MUTED);
 button(p,"Get a TypeSafe key",false,()->open("https://typesafe.ai/"));button(p,"VirusTotal account",false,()->open("https://www.virustotal.com/gui/join-us"));
 LinearLayout a=box();addText(a,"Jev Guard 0.1.0",18,INK);addText(a,"Independent personal prototype. Not affiliated with TypeSafe or VirusTotal. Static capability flags are hand-written review prompts; they are not a trained malware detector. Jev assessments are experimental. Keep Android's existing security protections enabled.",13,MUTED);}
 void open(String url){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url)));}catch(Exception e){toast("No browser available");}}
 void keyDialog(String id,String name){LinearLayout wrap=new LinearLayout(this);wrap.setOrientation(1);wrap.setPadding(dp(22),dp(10),dp(22),dp(10));addText(wrap,"Paste your own API key. Leave empty to keep the current key.",13,MUTED);EditText edit=new EditText(this);edit.setSingleLine(true);edit.setHint("API key");edit.setTextColor(INK);edit.setHintTextColor(MUTED);edit.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_VARIATION_PASSWORD);edit.setImportantForAutofill(View.IMPORTANT_FOR_AUTOFILL_NO);wrap.addView(edit);AlertDialog d=new AlertDialog.Builder(this).setTitle(name).setView(wrap).setNegativeButton("Cancel",null).setNeutralButton("Remove key",(x,w)->{try{secrets.put(id,"");show("Settings");}catch(Exception e){toast("Could not remove key");}}).setPositiveButton("Save",null).create();d.getWindow();d.setOnShowListener(x->{d.getWindow().addFlags(WindowManager.LayoutParams.FLAG_SECURE);d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{String value=edit.getText().toString().trim();if(value.isEmpty()){d.dismiss();return;}try{secrets.put(id,value);d.dismiss();show("Settings");}catch(Exception e){toast("Could not save key securely.");}});});d.show();}
 void loadHistory(){try{history=new JSONArray(getSharedPreferences("reports",0).getString("history","[]"));}catch(Exception e){history=new JSONArray();}}
 synchronized void save(JSONObject report)throws Exception{JSONArray next=new JSONArray();next.put(report);for(int i=0;i<history.length()&&next.length()<50;i++){JSONObject r=history.optJSONObject(i);if(r!=null&&!r.optString("id").equals(report.optString("id")))next.put(r);}if(!getSharedPreferences("reports",0).edit().putString("history",next.toString()).commit())throw new IOException("Could not save report");history=next;}
 @Override protected void onDestroy(){work.shutdownNow();super.onDestroy();}
}
